## 9022 - ssh port
---
- name: Install common and deps
  apt: pkg={{ item }} state=present
  with_items:
    - 'docker.io'

- name: Check that the docker service is started
  service: name=docker.io state=started