---
- name: Clone down latest node agent that can be used
  shell: rsync -aPzr node@hub.goddard.unicore.io:/var/goddard/agent/ /var/goddard/agent

- name: Write the new upstart script
  shell: cat /var/goddard/agent/scripts/boot.upstart.conf > /etc/init/goddardboot.conf

- name: Make init executable
  shell: chmod a+x /var/goddard/agent/scripts/init.sh

- name: Make setup executable
  shell: chmod a+x /var/goddard/agent/scripts/setup.sh

- name: Make provision executable
  shell: chmod a+x /var/goddard/agent/scripts/provision.sh

- name: Make boot executable
  shell: chmod a+x /var/goddard/agent/scripts/boot.sh

- name: Run provision on the node for initial config
  shell: cd /var/goddard/agent && ./scripts/provision.sh

- name: Start the setup service that will ensure all the apps are good
  service: name=goddardboot state=started
