## 9022 - ssh port
---
- name: Set correct hostname
  hostname: name={{inventory_hostname}}

- name: Add permanent hostname to /etc/hostname
  shell: echo "{{ inventory_hostname }}" > /etc/hostname

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/Africa/Johannesburg dest=/etc/localtime

- name: set /etc/timezone
  template: src=timezone dest=/etc/timezone

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: setup hostname
  template: src=hostname dest=/etc/hostname

- name: Update cache
  apt: update_cache=yes
  ignore_errors: yes

- name: Install common and deps
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - aptitude
    - git
    - htop
    - iftop
    - build-essential
    - python-setuptools
    - nginx

- name: Copy over nginx config
  template: src=nginx.site.conf dest=/etc/nginx/conf.d/default.conf

- name: Restart nginx to apply new config
  service: name=nginx state=restarted