## 9022 - ssh port
---
- name: Set correct hostname
  hostname: name={{inventory_hostname}}

- name: Add permanent hostname to /etc/hostname
  shell: echo "{{ inventory_hostname }}" > /etc/hostname

- name: setup hostname
  template: src=hostname dest=/etc/hostname

- name: Update cache
  apt: update_cache=yes
  ignore_errors: yes

- name: Install common and deps
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - aptitude
    - git
    - build-essential
    - python-setuptools
    - nginx